= qc through sensorthings API
:toc: left
:toc-interactive: // the active section will be highlighted
:toc-mode: offcanvas
:showtitle:
:icons: font

image::https://github.com/naturalsciences/qualityAssuranceTool/actions/workflows/python-app.yml/badge.svg?branch=main[Pytest_badge]



== Description

The goal of this project is to perform basic quality checks on data.
The project adds quality flags to the database (if configured).
The project should/will be structured that adding a new algorithm is as simple as changing a config file (yaml).


== Requirements

=== (Optional) SeaVox db

To query the sea region, seavox db is used.

== Installation

As it is a python project, no _real_ installation is needed, but a runtime python environment needs to be created where the needed packages are available.
The needed packages are listed in the file `requirements.txt`.

== Quality flags

The available flags are listed http://vocab.nerc.ac.uk/collection/L20/current/[here].
The _order_/_priority_ of the flags are determined by the order in which they are sorted in the link:src/models/enums.py[enum definition].

== Docker

=== Build image

```bash
docker buildx build --build-arg ID_U=$(id -u) -t qc_sensorthings . 
```

=== Run container

Run (single) docker container
```bash
source .env
docker run --rm --network=host -v ./conf:/app/conf -v ./outputs:/app/outputs -e DEV_SENSORS_USER=$DEV_SENSORS_USER -e DEV_SENSORS_PASS=$DEV_SENSORS_PASS qc_sensorthings "time.start=2023-06-01" "time.end=2023-07-01"
```

run multiple docker containers with different time periods
```bash
source .env
for f in $(seq -f "%02g" 1 11); do docker run --rm --network=host -v ./conf:/app/conf -v ./outputs:/app/outputs -e DEV_SENSORS_USER=$DEV_SENSORS_USER -e DEV_SENSORS_PASS=$DEV_SENSORS_PASS qc_sensorthings "time.start=2023-$((f))-01" "time.end=2023-$((f+1))-15"; done
```

```bash
source .env
for f in $(seq -f "%02g" 1 11); do fp1=$((f+1)); ff=$(printf "%02d" $f); fp1f=$(printf "%02d" $fp1); docker run --rm --name=QC_$ff --network=host -v ./conf:/app/conf -v ./outputs:/app/outputs -e DEV_SENSORS_USER=$DEV_SENSORS_USER -e DEV_SENSORS_PASS=$DEV_SENSORS_PASS qc_sensorthings "time.start=2023-$ff-01" "time.end=2023-$fp1f-15"; done
```

== __Possible__ quality checks

=== Regions

1. The location associated with each observation is compared with the SeaVox database.
A region and sub-region (lowest found level) are associated with the location.
2. The name is verified to not contain *mainland*. These are marked as bad

WARNING: the layers don't seem to follow the coastlines very accurately. For _internal_ waters in for example Iceland and Greenland, a lot of location return None. These location get a *probably bad* flag.

=== Locations

==== Velocity

The velocity, calculated based on the distance traveled from the current point to the next is compared with a maximal (allowed) velocity.
When a single record is flagged, it is possibly an issue with the timestamp.
If two or more records are flagged, it is possibly related  to the gps location.

==== Acceleration

The acceleration, calculated from the difference between consecutive distances (calculated between this and the next point) are compared with a maximal acceleration value.
One incorrect location, can give rise to multiple flagged records.

==== Outliers

A rolling windows (see pandas documentation for more information) is used to calculate the median latitude and longitude.
Then each location is compared with the median location.
This distance is compared with the max distance within the considered window.

NOTE: This solution is not ideal.
Calculating the angle between each line segment and comparing with a threshold might be better. 
This value will however be a function of the sample frequency and velocity.

=== Bedrock height

The sea region detection described in <<Regions>> sometimes fails to label points close to the coast, in a harbour or in _internal_ waters (Iceland and Greenland).
Therefore a second test is included that determines the bedrock height at all points.
Doing so, one can for example set the flag to _Probably good_ if no region is identified, *but* the depth is below a threshold value.

=== Range

This test verifies that the range (min/max) of the measurement is correct.
It is planned to allow for location dependent ranges.

=== Gradient

The https://numpy.org/doc/stable/reference/generated/numpy.gradient.html[gradient] over time is calculated.
If the gradient is outside of a given range, the result is flagged.

=== Dependent

The accuracy, quality or validity of some measurements depends on other quantities.
To link the independent and dependent values, a difference between the *timestamps* of maximum 0.5 seconds is allowed.

There are two possible dependencies:

Directly linked flags:: the measurement of the dependent quantity need to assume the same flag as the independent quantity measurement (at the same time), if this flag is different from `Good` or `No Quality Control`.
If the measured water temperature is impossible, the dependent salinity measurement can't possibly be correct.
Quality check:: the measurement of the dependent quantity needs to be set according to the *value* of the independent quantity measurement (at the same time).
The difference with the first dependent qc, is that the flags themselves are not _linked_.
The flow of a scientific water circuit can be measured correctly to be zero (flagged as `Good`), but the dependent quantity measurements can't possible be correct!

== Configuration

This project uses hydra for (most) configurations and is done through a yaml file.
All config files can be found in the `conf` folder.

hydra::
    verbose:::
        Log level (True or \\__main__)
data_api::
    base_url::: url to the sensorthings instance
    things::: 
        id:::: thing identifier (integer)
    filter:::
        phenomenonTime:::: 
            format::::: expression how time/date is formatted (for example"%Y-%m-%d %H:%M" )
            range::::: start and end date/time following specified format
location::
    connection:::
        database:::: postgresql database name
        user:::: user name 
        host:::: hostname
        port:::: port that is used
        passphrase:::: passphrase for user
    crs::: crs of db (EPS:4326)
    time_window::: The time window used for the _rolling median_.
    max_dx_dt::: The maximal velocity of the vessel, used for outlier detection.
QC_dependent:: *list* if quantity dependent relations. 2 _checks_ can be performed. If the independent quantity has a quality flag different from _good_, the dependent quantity wil get the same label (in the default use case. This can also be changed in the main file). 
    independent::: identifier (sensorthings) of independent quantity
    dependent::: identifier (sensorthings) of dependent quantity
    QC::: type of quality check (only range is implemented)
        range:::: list of *2* values (min, max)
QC:: _normal_ quality checks. only two are defined: range and gradient
    name::: the *name* of the observed feature
    range::: expected range of the feature values
    gradient::: expected range of the *gradient*.

== License

link:LICENSE[License file]

