= qc through sensorthings API
:toc: 
:showtitle:


== Description

The goal of this project is to perform basic quality checks on data. The
project adds quality flags to the database (if configured). The project
should/will be structured that adding a new algorithm is as simple as
changing a config file (yaml).

== Installation

As it is a python project, no _real_ installation is needed, but a
runtime python environment needs to be created where the needed packages
are available. The needed packages are listed in the file
`requirements.txt`.

=== Linux

When working on a linux kernel, the setup and the running of the project
can be done through `make`.

=== Windows

No install script if foreseen for windows.

== Usage

== Roadmap

== License

== Project status

=== inspect return obj restructure

* out -> dict
** Thing
*** name
*** @iot.id
** Datastreams
*** name
**** @iot.id
**** unitOfMeasurement
*** ObservedProperty
**** name
***** @iot.id
*** Observations
**** count

== ToDo

* [ ] JSON schema yaml
* [ ] extend QC checks
* [ ] asynchronous requests?
* [ ] refactoring
    ** [ ] restructure based on function
    ** [ ] reevaluate variable names
    ** [ ] merge with FROST-docker repo (github)
* [ ] docs
    ** [ ] extend documentation
* [ ] testing
    ** [ ] unit tests
    ** [ ] integration tests
    ** [ ] check pipelines/hooks/... on gitlab

== Questions

* observedArea
** are the coordinates based on the coordinates of the observations? or
preset? If preset, could be checked if in box
** what coordinate reference system is used?
** ?

== Batch

`curl -H "Content-Type: application/json" -d @/tmp/test.json "http://localhost:8080/FROST-Server/v1.1/\$batch"`

with test.json: \{ ``requests'': [ \{ ``id'': ``0'', ``atomicityGroup'':
``group1'', ``method'': ``post'', ``url'': ``Things'', ``body'': \{
``name'': ``stuff'', ``description'': ``looser'' } }, \{ ``id'': ``1'',
``method'': ``get'', ``atomicityGroup'':``group2'', ``url'':
``Datastreams(1)'' } ] }

.(Partial) logs batch patch
[source,plain]
----
[2023-07-12 08:51:48,584][__main__][INFO] - Start batch patch query
[2023-07-12 08:52:21,739][__main__][INFO] - End batch patch query
[2023-07-12 08:52:21,739][__main__][INFO] - Counter({200: 17673})
----

== geo

https://rda.ucar.edu/datasets/ds759.3/dataaccess/