time: 
  format: "%Y-%m-%d %H:%M"
  start: 2023-01-01 00:00
  end: 2024-01-01 00:00
  window: 1month
  date:
    format: "%Y-%m-%d"
hydra:
  # verbose: True
  verbose: __main__
  run:
    dir: outputs/counter/${datetime_to_date:${time.start}, ${time.format},${time.date.format}}_${datetime_to_date:${time.end}, ${time.format},${time.date.format}}_${time.window}
data_api:
  base_url: https://belgica11busta.rbins.be/FROST-Server/v1.1
  # base_url: https://sensors.naturalsciences.be/sta/v1.1
  # base_url: http://localhost:8080/FROST-Server/v1.1
  # base_url: http://192.168.0.25:8080/FROST-Server/v1.1
  # base_url: http://frost-docker_frosty_net:8080/FROST-Server/v1.1
  # base_url: https://dev-sensors.naturalsciences.be/sta/v1.1
  auth:
    username: ${oc.env:DEV_SENSORS_USER}
    passphrase: ${oc.env:DEV_SENSORS_PASS}
  things:
    id: 1
  filter:
    phenomenonTime:
      format: ${time.format}
      range:
        - ${time.start}
        - ${time.end}
