time: 
  format: "%Y-%m-%d %H:%M:%S"
  # start: "2024-03-12 09:00:00"
  # end: "2024-04-12 12:00:00"
  start: "2024-03-19 12:31:00"
  end: "2024-03-19 12:31:30"
  date:
    format: "%Y-%m-%d"
hydra:
  # verbose: True
  verbose: __main__
  run:
    dir: outputs/${datetime_to_date:${time.start}, ${time.format},${time.date.format}}_${datetime_to_date:${time.end}, ${time.format},${time.date.format}}
data_api:
  # base_url: https://sensors.naturalsciences.be/sta/v1.1
  # base_url: "http://localhost:8080/FROST-Server/v1.1/"
  # base_url: http://192.168.0.25:8080/FROST-Server/v1.1
  # base_url: http://frost-docker_frosty_net:8080/FROST-Server/v1.1
  base_url: https://dev-sensors.naturalsciences.be/sta/v1.1
  # base_url: "https://belgica11busta.rbins.be/FROST-Server/v1.1/"
  auth:
    username: ${oc.env:DEV_SENSORS_USER,""}
    passphrase: ${oc.env:DEV_SENSORS_PASS,""}
  things:
    id: 1
  filter:
    phenomenonTime:
      format: ${time.format}
      range:
        - ${time.start}
        - ${time.end}
reset:
  overwrite_flags: True
  observation_flags: True
  feature_flags: True
  exit: True
other:
  count_observations: False
location:
  # connection:
  #   database: seavox_areas
  #   user: sevox
  #   host: localhost
  #   # port: 5432
  #   port: 8901
  #   passphrase: ChangeMe
  crs: EPSG:4326 # not fully used
  time_window: 10min
  max_dx_dt: 6.89 # check units
  max_ddx_dtdt: 0.15 # VERY high value, needs to be re-evaluated when shorted time intervals are available
QC_dependent:
  - independent: 7793 #water flow in the thermofluor #1
    dependent: 7767,7768,7792,7846,7847,7848
    dt_tolerance: 0.5s
    QC:
      range:
       - 0.5
       - 10.
  - independent: 7795 #water flow in the thermofluor #2
    dependent: 7769,7770,7794,7849,7850,7851
    dt_tolerance: 0.5s
    QC:
      range:
       - 0.5
       - 10.
  - independent: 7824 #water flow in the AUMS
    dependent: 7810,7811,7812,7813,7814,7815,7816,7817,7818,7820,7821,7822,7823,7826,7827,7828,7829,7831    
    dt_tolerance: 0.5s
    QC:
      range:
       - 0.5
       - 10.
  - independent: 7971 #Sensor status AUMS
    dependent: 7810,7811,7812,7813,7814,7815,7816,7817,7818,7820,7821,7822,7823,7826,7827,7828,7829,7831    
    dt_tolerance: 0.5s
    QC:
      range:
       - 4.9
       - 5.1
  - independent: 7768 #Water temperature SBE38 measured by the sensor ThermoFluor 1 before the SSW pump (SBE21 #1)
    dependent: 7847
    dt_tolerance: 0.5s
    QC:
      range: 
        - -2
        - 30
      zscore:
        - -15
        - 15
  - independent: 7846 #Conductivity measured by the sensor ThermoFluor 1 (SBE21 #1)
    dependent: 7847
    dt_tolerance: 0.5s    
    QC:
      range: 
        - 0
        - 6
      zscore:
        - -15
        - 15
  - independent: 7770 #Water temperature SBE38 measured by the sensor ThermoFluor 2 before the SSW pump (SBE21 #2)
    dependent: 7850
    dt_tolerance: 0.5s    
    QC:
      range: 
        - -2
        - 30
      zscore:
        - -15
        - 15
  - independent: 7849 #Conductivity measured by the sensor ThermoFluor 2 (SBE21 #2)
    dependent: 7850
    dt_tolerance: 0.5s    
    QC:
      range: 
        - 0
        - 6
      zscore:
        - -15
        - 15
QC:
  - id: 7727 #Telegram VTG measured by the sensor GPS 1 (R5 #1)
    range: 
      - 0
      - 360
  - id: 7728 #Telegram VTG measured by the sensor GPS 1 (R5 #1)
    range: 
      - -5
      - 18
  - id: 7738 #Depth from transducer measured by the sensor Depth Sounder (ESN200)
    range: 
      - 5
      - 5000
    zscore:
      - -3
      - 3
  - id: 7739 #Depth from surface measured by the sensor Depth Sounder (ESN200)
    range: 
      - 5
      - 5000
    zscore:
      - -3
      - 3
  - id: 7741 #Depth measured by the sensor Depth Sounder (ESN200)
    range: 
      - 5
      - 5000
    zscore:
      - -3
      - 3
  - id: 7743 #True heading measured by the sensor Speed Log (EML224)
    range: 
      - 0
      - 360
  - id: 7744 #Magnetic heading measured by the sensor Speed Log (EML224)
    range: 
      - 0
      - 360
  - id: 7747 #Wind angle measured by the sensor WeatherStation (CR6 WS #1)
    range: 
      - 0
      - 360
  - id: 7748 #Wind speed measured by the sensor WeatherStation (CR6 WS #1)
    range: 
      - 0
      - 60
  - id: 7749 #Air temperature measured by the sensor WeatherStation (CR6 WS #1)
    range: 
      - -20
      - 40
  - id: 7750 #Relative humidity measured by the sensor WeatherStation (CR6 WS #1)
    range: 
      - 0
      - 100
  - id: 7751 #True wind speed measured by the sensor WeatherStation (CR6 WS #1)
    range: 
      - 0
      - 60
  - id: 7752 #True wind direction measured by the sensor WeatherStation (CR6 WS #1)
    range: 
      - 0
      - 360
  - id: 7753 #Air pressure measured by the sensor WeatherStation (CR6 WS #1)
    range: 
      - 800
      - 1084.8
  - id: 7754 #Solar radiation density measured by the sensor WeatherStation (CR6 WS #1)
    range: 
      - 0
      - 1200
  - id: 7756 #18kHz - Depth measured by the sensor EK80
    range: 
      - 5
      - 7000
    zscore:
      - -3
      - 3
  - id: 7759 #38kHz - Depth measured by the sensor EK80
    range: 
      - 5
      - 2800
    zscore:
      - -3
      - 3
  - id: 7763 #70kHz - Depth measured by the sensor EK80
    range: 
      - 5
      - 1100
    zscore:
      - -3
      - 3
  - id: 7766 #120kHz - Depth measured by the sensor EK80
    range: 
      - 5
      - 850
    zscore:
      - -3
      - 3
  - id: 7767 #Water temperature SBE21 measured by the sensor ThermoFluor 1 after the SSW pump (SBE21 #1)
    range: 
      - -2
      - 30
    zscore:
      - -15
      - 15
  - id: 7769 #Water temperature SBE21 measured by the sensor ThermoFluor 2 after the SSW pump (SBE21 #2)
    range: 
      - -2
      - 30
    zscore:
      - -15
      - 15
  - id: 7773 #200kHz - Depth measured by the sensor EK80
    range: 
      - 5
      - 550
    zscore:
      - -3
      - 3
  - id: 7776 #333kHz - Depth measured by the sensor EK80
    range: 
      - 5
      - 500
    zscore:
      - -3
      - 3
  - id: 7792 #SV chen millero measured by the sensor ThermoFluor 1 (SBE21 #1)
    range: 
      - 1400
      - 1600
  - id: 7794 #SV chen millero measured by the sensor ThermoFluor 2 (SBE21 #2)
    range: 
      - 1400
      - 1600
  - id: 7800 #Wind angle measured by the sensor WeatherStation2 (CR6 WS #2)
    range: 
      - 0
      - 360
  - id: 7801 #Wind speed measured by the sensor WeatherStation2 (CR6 WS #2)
    range: 
      - 0
      - 60
  - id: 7802 #Air temperature measured by the sensor WeatherStation2 (CR6 WS #2)
    range: 
      - -20
      - 40
  - id: 7803 #Relative humidity measured by the sensor WeatherStation2 (CR6 WS #2)
    range: 
      - 0
      - 100
  - id: 7804 #True wind speed measured by the sensor WeatherStation2 (CR6 WS #2)
    range: 
      - 0
      - 60
  - id: 7805 #True wind direction measured by the sensor WeatherStation2 (CR6 WS #2)
    range: 
      - 0
      - 360
  - id: 7806 #Air pressure measured by the sensor WeatherStation2 (CR6 WS #2)
    range: 
      - 800
      - 1084.8
  - id: 7807 #Solar radiation density measured by the sensor WeatherStation2 (CR6 WS #2)
    range: 
      - 0
      - 1200
  - id: 7810 #Temperature SBE45 measured by the sensor SubCtech OceanPack AUMS
    range: 
      - -2
      - 30
    zscore:
      - -15
      - 15
  - id: 7812 #Salinity SBE45 measured by the sensor SubCtech OceanPack AUMS
    range: 
      - 0
      - 40
    zscore:
      - -15
      - 15
  - id: 7814 #O2 saturation measured by the sensor SubCtech OceanPack AUMS
    range: 
      - 0
      - 100
  - id: 7847 #Salinity measured by the sensor ThermoFluor 1 (SBE21 #1)
    range: 
      - 2
      - 40
    zscore:
      - -15
      - 15
  - id: 7848 #Density sigma-theta measured by the sensor ThermoFluor 1 (SBE21 #1)
    range: 
      - 3
      - 30
  - id: 7850 #Salinity measured by the sensor ThermoFluor 2 (SBE21 #2)
    range: 
      - 2
      - 40
    zscore:
      - -15
      - 15
  - id: 7851 #Density sigma-theta measured by the sensor ThermoFluor 2 (SBE21 #2)
    range: 
      - 3
      - 30
  - id: 7852 #Telegram VTG measured by the sensor GPS 2 (R5 #2)
    range: 
      - 0
      - 360
  - id: 7853 #Telegram VTG measured by the sensor GPS 2 (R5 #2)
    range: 
      - -5
      - 18
  - id: 7854 #Telegram VTG measured by the sensor Seapath (380-R3)
    range: 
      - 0
      - 360
  - id: 7855 #Telegram VTG measured by the sensor Seapath (380-R3)
    range: 
      - -5
      - 18
  - id: 7856 #Telegram HDT measured by the sensor Seapath (380-R3)
    range: 
      - 0
      - 360
  - id: 7859 #Telegram SXN23 measured by the sensor Seapath (380-R3)
    range: 
      - 0
      - 360
  - id: 7861 #Telegram HDT measured by the sensor Gyro 2 (Navigat 200 #2)
    range: 
      - 0
      - 360
  - id: 7865 #Heading measured by the sensor EM3000 MRU 1 (IMU-108 #1)
    range: 
      - 0
      - 360
  - id: 7869 #Heading measured by the sensor EM3000 MRU 1 (IMU-108 #2)
    range: 
      - 0
      - 360
  - id: 7870 #Telegram HDT measured by the sensor Gyro 1 (Navigat 200 #1)
    range: 
      - 0
      - 360
