time: 
  format: "%Y-%m-%d %H:%M"
  # start: "2024-03-12 09:00"
  # end: "2024-04-12 12:00"
  # start: "2024-03-17 23:00"
  start: "2024-03-19 12:29"
  # end: "2024-03-19 23:00"
  end: "2024-03-19 13:00"
  date:
    format: "%Y-%m-%d"
hydra:
  verbose: True
  # verbose: __main__
  run:
    dir: outputs/${datetime_to_date:${time.start}, ${time.format},${time.date.format}}_${datetime_to_date:${time.end}, ${time.format},${time.date.format}}
data_api:
  # base_url: https://sensors.naturalsciences.be/sta/v1.1
  # base_url: http://localhost:8080/FROST-Server/v1.1
  # base_url: http://192.168.0.25:8080/FROST-Server/v1.1
  # base_url: http://frost-docker_frosty_net:8080/FROST-Server/v1.1
  # base_url: https://dev-sensors.naturalsciences.be/sta/v1.1
  base_url: https://belgica11busta.rbins.be/FROST-Server/v1.1
  auth:
    username: ${oc.env:DEV_SENSORS_USER,""}
    passphrase: ${oc.env:DEV_SENSORS_PASS,""}
  things:
    id: 1
  filter:
    phenomenonTime:
      format: ${time.format}
      range:
        - ${time.start}
        - ${time.end}
reset:
  overwrite_flags: False
  observation_flags: False
  feature_flags: False
  exit: False
location:
  # connection:
  #   database: seavox_areas
  #   user: sevox
  #   host: localhost
  #   # port: 5432
  #   port: 8901
  #   passphrase: ChangeMe
  crs: EPSG:4326 # not fully used
  time_window: 30min
  max_dx_dt: 6.89 # check units
  max_ddx_dtdt: 0.15 # VERY high value, needs to be re-evaluated when shorted time intervals are available
QC_dependent:
  - independent: 69
    dependent: 124 # list/array
    dt_tolerance: 0.5s
    QC:
      range:
        - 0.5
        - 10.
QC:
  7847:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7768:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7850: # salinity
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7770: # water temperature
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -15
      - 15
  7849: # conductivity
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7846:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7848:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7851: # sigma-t
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7792:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7794:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7739: # seabed depth (0)
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -3
      - 3
  7738:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7741:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7766:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7816: # pH
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7756: # seabed depth
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7773:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7776:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7759: # seabed depth
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7763: # seabed depth
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7821:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7819:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7813: # dissolved O2 concentration
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7823:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100
  7826:
    range:
      - -1000000000
      - 1000000000
    zscore:
      - -100
      - 100