time: 
  format: "%Y-%m-%d %H:%M"
  # start: 2023-07-24 00:00
  # end: 2023-07-24 10:00
  start: 2023-08-22 10:00
  end: 2023-08-22 12:41
  # end: 2023-08-22 10:11
  date:
    format: "%Y-%m-%d_%H:%M"
hydra:
  # verbose: True
  verbose: __main__
  job:
    chdir: True
  run:
    dir: outputs/data_requests/${datetime_to_date:${time.start}, ${time.format},${time.date.format}}_${datetime_to_date:${time.end}, ${time.format},${time.date.format}}
data_api:
  # base_url: https://sensors.naturalsciences.be/sta/v1.1
  # base_url: http://localhost:8080/FROST-Server/v1.1
  # base_url: http://192.168.0.25:8080/FROST-Server/v1.1
  # base_url: http://frost-docker_frosty_net:8080/FROST-Server/v1.1
  # base_url: https://dev-sensors.naturalsciences.be/sta/v1.1
  base_url: https://belgica11busta.rbins.be/FROST-Server/v1.1
  things:
    id: 1
  filter:
    phenomenonTime:
      format: ${time.format}
      range:
        - ${time.start}
        - ${time.end}
    datastreams:
      - 7751
      - 7752
      - 7769
      - 7770
      - 7849
      - 7850
      - 7851
      - 7854
      - 7855
csv_file: ./requested_data_${now:%Y-%m-%d_%H%M}.csv