hydra:
  # verbose: True
  verbose: __main__
data_api:
  # base_url: https://sensors.naturalsciences.be/sta/v1.1
  base_url: http://localhost:8080/FROST-Server/v1.1
  things:
    id: 1
  datastreams:
    top: 10
  observations:
    top: 100000
  filter:
    phenomenonTime:
      format: "%Y-%m-%d %H:%M"
      range:
        - 2023-07-10 12:00
        - 3003-01-01 00:00
other:
  pickle:
    path: ${hydra:runtime.cwd}/features.pkl
# example, not yet implemented
QC_dependent:
  - independent: 69
    dependent: 124
    QC:
      range:
        - 0.5
        - 10.
QC:
  seabed depth:
    range:
      - 0.
      - 10000.
    gradient:
      - -1e5
      - 1e5
  bottom hardness:
    range:
      - -100
      - 0
  altitude above sea bed:
    range:
      - 0.
      - 10000.
  atmospheric pressure:
    range:
      - 870.
      - 1084.8
  Speed of wind {wind speed} in the atmosphere by in-situ anemometer:
    range:
      - 0.
      - 115.
  ship speed:
    range:
      - 0.
      - 13.
  downwelling irradiance in the atmosphere:
    range:
      - 0.
      - 440.
  conductivity:
    range:
      - 3.
      - 6.
  water temperature:
    range:
      - -2.
      - 30.
  salinity:
    range:
      - 29.
      - 36.
  Total biomass in water bodies:
    range:
      - 0.
      - 3429904.
  heading: # don't understand this. shouldn't this be -180 to 180?
    range:
      - 0.
      - 360.
  speed over ground:
    range:
      - 0.
      - 10.
  Pressure (measured variable) exerted by the water body plus atmosphere:
    range:
      - 3.
      - 5.
  Direction (towards) of wind relative to True North in the atmosphere by in-situ anemometer:
    range:
      - 4.
      - 352.
  atmospheric temperature:
    range:
      - -20.
      - 40.
  chlorophyll concentration:
    range:
      - 0.
      - 20.
  Depth (spatial coordinate) relative to water surface in the water body by physical measurement:
    range:
      - 0.
      - 1500.
  Water flow in the scientific seawater circuit:
    range:
      - 0.
      - 10.
  sigma-t:
    range:
      - 3.
      - 1030.
  photosynthetically active radiation in the water column:
    range:
      - 0.5
      - 700.
  dissolved O₂ concentration:
    range:
      - 0.3 # seems too low? or is very deep?
      - 352.
  atmospheric humidity:
    range:
      - 25
      - 100
  suspended matter concentration:
    range:
      - 0. # most values are negative
      - 6000.

ignored:
  Sound velocity in the water body: # strange values

  CDOM concentration: # no observations?
  Speed of wind {wind speed} in the atmosphere: # no observations?
  partial CO₂ pressure:
  Offset (THIS NEEDS MORE EXPLANATION!):
  pH:
  Sensor Status LI-COR:
  Direction (from) of wind relative to moving platform and heading {wind direction} in the atmosphere by in-situ anemometer:
