data_api:
  base_url: https://sensors.naturalsciences.be/sta/v1.1
  things:
    id: 1
QC:
  seabed depth:
    range:
      - 0.
      - 10000.
  bottom hardness:
    range:
      - -100
      - 0
  altitude above sea bed:
    range:
      - 0.
      - 10000.
  atmospheric pressure:
    range:
      - 870.
      - 1084.8
  Speed of wind {wind speed} in the atmosphere by in-situ anemometer:
    range:
      - 0.
      - 115.
  ship speed:
    range:
      - 0.
      - 13.
  downwelling irradiance in the atmosphere:
    range:
      - 0.
      - 440.
  conductivity:
    range:
      - 3.
      - 6.
  water temperature:
    range:
      - -2.
      - 30.
  salinity:
    range:
      - 29.
      - 36.
  Total biomass in water bodies:
    range:
      - 0.
      - 3429904.
  heading: # don't understand this. shouldn't this be -180 to 180?
    range:
      - -1.6
      - 15.
  speed over ground:
    range:
      - 0.
      - 10.
other:
  Pressure (measured variable) exerted by the water body plus atmosphere:
  CDOM concentration:
  Direction (towards) of wind relative to True North in the atmosphere by in-situ anemometer:
  Speed of wind {wind speed} in the atmosphere:
  atmospheric temperature:
  partial CO₂ pressure:
  Offset (THIS NEEDS MORE EXPLANATION!):
  chlorophyll concentration:
  Depth (spatial coordinate) relative to water surface in the water body by physical measurement:
  Sound velocity in the water body:
  sigma-t:
  photosynthetically active radiation in the water column:
  Direction (from) of wind relative to moving platform and heading {wind direction} in the atmosphere by in-situ anemometer:
  Water flow in the scientific seawater circuit:
  dissolved O₂ concentration:
  atmospheric humidity:
  pH:
  suspended matter concentration:
  Sensor Status LI-COR:
